// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BuscarCorridas: typeof import('./src/components/BuscarCorridas.vue')['default']
    CityInput: typeof import('./src/components/UiElements/CityInput.vue')['default']
    copy: typeof import('./src/components/UiElements/SelectInput copy.vue')['default']
    EventCard: typeof import('./src/components/UiElements/EventCard.vue')['default']
    Events: typeof import('./src/components/Events.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PaginationEvents: typeof import('./src/components/PaginationEvents.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectInput: typeof import('./src/components/UiElements/SelectInput.vue')['default']
    StateInput: typeof import('./src/components/UiElements/StateInput.vue')['default']
    TextInput: typeof import('./src/components/UiElements/TextInput.vue')['default']
    UserDropdown: typeof import('./src/components/UiElements/UserDropdown.vue')['default']
  }
}
