// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BuscarCorridas: typeof import('./src/components/BuscarCorridas.vue')['default']
    CityInput: typeof import('./src/components/UiElements/CityInput.vue')['default']
    EventCard: typeof import('./src/components/UiElements/EventCard.vue')['default']
    Events: typeof import('./src/components/Events.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Pagination: typeof import('./src/components/UiElements/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateInput: typeof import('./src/components/UiElements/StateInput.vue')['default']
    TextInput: typeof import('./src/components/UiElements/TextInput.vue')['default']
    UserDropdown: typeof import('./src/components/UiElements/UserDropdown.vue')['default']
  }
}
